site_name: Steam Project Documentation
nav:
  - Home: index.md
  - Installation: Installation.ipynb
  - Getting Started: GettingStarted.ipynb
  - Feature Documentation: Feature Documentation.ipynb
  - GamesFromPublisher: GamesFromPublisher.ipynb
  - GamesInGenre: GamesInGenre.ipynb
  - GenreOfPublisher: GenreOfPublisher.ipynb
  - SumReviews: SumReviews.ipynb
  - ReceptionByGenre: ReceptionByGenre.ipynb
  - Top100: Top100.ipynb
  - PublisherGraph: PublisherGraph.ipynb
  - PlaytimeByGenre: PlaytimeByGenre.ipynb
  - CleanGames: CleanGames.ipynb  
  - Contributing Guide: Contributing Guide.ipynb
  

theme: readthedocs
plugins:
  - mkdocs-jupyter