site_name: Steam Project Documentation
nav:
  - Home: index.md
  - GamesFromPublisher: GamesFromPublisher.ipynb
  - GamesInGenre: GamesInGenre.ipynb
  - GenreOfPublisher: GenreOfPublisher.ipynb
  - SumReviews: SumReviews.ipynb
  - ReceptionByGenre: ReceptionByGenre.ipynb
  - Top100: Top100.ipynb
  - PublisherGraph: PublisherGraph.ipynb

theme: readthedocs
plugins:
  - mkdocs-jupyter